//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCT_HoaDon
    {
        public int ID { get; set; }
        public string MaHoaDon { get; set; }
        public string MaSanPham { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public int SoLuong { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
