//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDon()
        {
            this.tblCT_HoaDon = new HashSet<tblCT_HoaDon>();
        }
    
        public string MaHD { get; set; }
        public string NhanVienLapHD { get; set; }
        public Nullable<System.DateTime> NgayLapHoaDon { get; set; }
        public string MaKhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCT_HoaDon> tblCT_HoaDon { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblKhachHang tblKhachHang1 { get; set; }
    }
}
