//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSanPham()
        {
            this.tblCT_HoaDon = new HashSet<tblCT_HoaDon>();
        }
    
        public Nullable<int> TrangThai { get; set; }
        public string MaSp { get; set; }
        public string TenSp { get; set; }
        public string AnhMinhHoa { get; set; }
        public string DonViTinh { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public string MaNhaCungCap { get; set; }
        public System.DateTime NgaySanXuat { get; set; }
        public System.DateTime HanSuDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCT_HoaDon> tblCT_HoaDon { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
    }
}
