//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaiKhoan
    {
        public int TrangThai { get; set; }
        public string Ma_NVien { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string MaChucVu { get; set; }
    
        public virtual tblChucVu tblChucVu { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
